📝  documenter les dependence
Zenika/grenoble-hands-on-vuejs pull request #11
Opened 2020-10-03 14:48 UTC by chocho01

Ajout d'une section pour lister les dépendances utiliser avec un lien vers la doc

2020-10-03 18:03 UTC, P0ppoff requested changes

2020-10-03 18:03 UTC, P0ppoff commented on README.md
> +- Framework: [Vue 3](https://v3.vuejs.org/guide)
Si tu met Vue `3` il faut mettre les version de *vuex* et du *vue-router* aussi car elles sont spécifiques à la dernière version de vue. Je serais plutôt chaud pour ne pas mettre de version et par le dire à haute voix à la fin comme quoi on utilise l'écosystème de Vue3

2020-10-04 08:32 UTC, chocho01 commented on README.md
> +- Framework: [Vue 3](https://v3.vuejs.org/guide)
Yes pas con!

2020-10-04 08:47 UTC, P0ppoff approved these changes

2020-10-04 08:48 UTC, merged