fix typos and add parsedate util
Zenika/grenoble-hands-on-vuejs pull request #18
Opened 2020-10-12 07:18 UTC by thuchede

Since the date format is not that great to read from, I'll throw in some `parseDate` function to display/manipulate the date more easily.

2020-10-12 16:14 UTC, P0ppoff requested changes

2020-10-12 16:14 UTC, P0ppoff commented on src/utils/date.js
> +}
J’avais commencé à utiliser [date-fns](https://github.com/Zenika/grenoble-hands-on-vuejs/blob/master/package.json#L13) mais je crois que ça a sauté au moment de la réduction, on choisi quoi ? une méthode ou une lib ?

2020-10-12 16:14 UTC, P0ppoff commented on README.md
> +
ça chance un truc côté présentation ?

2020-10-12 16:36 UTC, chocho01 approved these changes
Ok pour moi mais effectivement ça sera un petit plus en utilisant date-fns

2020-10-12 16:36 UTC, chocho01 commented on src/utils/date.js
> +}
yes il y a une dépendance vers `date-fns`
Ca vaut peut etre le coup de la garder pour ceux qui veulent s'amuser avec la date : 
```
format(parse(date, 'yyyyMMdd', new Date()), 'dd/MM/yyyy')
```

2020-10-12 19:25 UTC, thuchede commented on README.md
> +
non, j'ai du taper un retour de trop ici, je le retire

2020-10-12 19:27 UTC, thuchede commented on src/utils/date.js
> +}
J'ai pas pensé qu'on avait une dep vers date-fns et je n'ai pas pensé à vérifier : ça rends inutile mon helper je retire 🤓

2020-10-13 07:14 UTC, P0ppoff commented on src/utils/date.js
> +}
J’aurais quand même bien fait le helper avec `date-fns` pour leur montrer un exemple. Dans une autre PR ?

2020-10-13 07:15 UTC, P0ppoff approved these changes

2020-10-13 07:15 UTC, merged